module.exports = {
  CLIENT_EVENTS: {
    REGISTER: 'REGISTER',
    HEARTBEAT: 'HEARTBEAT',
    LOCATION_UPDATE: 'LOCATION_UPDATE',
    HARASSMENT_DETECTED: 'HARASSMENT_DETECTED',
    SOS_RAISED: 'SOS_RAISED'
  },
  SERVER_EVENTS: {
    REGISTERED: 'REGISTERED',
    ERROR: 'ERROR',
    LIVE_LOCATION_UPDATE: 'LIVE_LOCATION_UPDATE',
    HARASSMENT_FLAG: 'HARASSMENT_FLAG',
    SOS_TRIGGERED: 'SOS_TRIGGERED',
    MEDIA_AVAILABLE: 'MEDIA_AVAILABLE',
    DEVICE_DISCONNECTED: 'DEVICE_DISCONNECTED'
  }
};
